/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.registro;

import com.mycompany.crudsqlserver.java.ConexionSQLServer;
import com.principal.principalRegistro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class registroVehiculo extends javax.swing.JFrame {
    private String num_matricula;
    /**
     * Creates new form registroCliente
     */
    public registroVehiculo() {
        initComponents();
        
            
    }
private boolean insertarMatricula(String tabla , String num_matricula ) {
        this.num_matricula = num_matricula;
        String sql = "INSERT INTO " + tabla + " (num_matricula) VALUES (?)";
        ConexionSQLServer con = new ConexionSQLServer();
        Connection conexion = con.obtenerConexion();

    
        try {
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, num_matricula);

            int rows = ps.executeUpdate();

            if (rows > 0) {
                System.out.println("Matrícula insertada con éxito");
                return true;
            } else {
                System.out.println("Error al insertar matrícula");
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
    
    
        }
        return false;
}

    
    
  
    public void insertar(String tabla, String id_taller,
        String nombre_cliente, String apellido_cliente, String fecha_compra,
        String marca, String modelo, String anio) {
        int anio1 = Integer.parseInt(anio);
        
        String sql = "INSERT INTO " + tabla + " (num_matricula, id_taller, nombre_cliente, apellido_cliente, fecha_compra, marca, modelo, anio) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        ConexionSQLServer con = new ConexionSQLServer();
        Connection conexion = con.obtenerConexion();

        try {
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, num_matricula);
            ps.setString(2, id_taller);
            ps.setString(3, nombre_cliente);
            ps.setString(4, apellido_cliente);
            ps.setString(5, fecha_compra);
            ps.setString(6, marca);
            ps.setString(7, modelo);
            ps.setInt(8, anio1);

            int rows = ps.executeUpdate();

            if (rows > 0) {
                System.out.println("Insertado con éxito");
            } else {
                System.out.println("Error al insertar");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JTextField();
        botonAtras = new javax.swing.JTextField();
        txtField_modelo = new java.awt.TextField();
        txtField_nombre = new java.awt.TextField();
        txtField_matricula = new java.awt.TextField();
        txtField_anio = new java.awt.TextField();
        txtField_marca = new java.awt.TextField();
        txtField_apellido = new java.awt.TextField();
        lbl_titulo = new javax.swing.JLabel();
        lbl_matricula = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        lbl_anio = new javax.swing.JLabel();
        lbl_anio1 = new javax.swing.JLabel();
        txtField_fechaCompra = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EPN CAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        lbl_nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_nombre.setText("NOMBRE");

        botonRegistrar.setEditable(false);
        botonRegistrar.setBackground(new java.awt.Color(231, 231, 231));
        botonRegistrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonRegistrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonRegistrar.setText("REGISTRAR");
        botonRegistrar.setAutoscrolls(false);
        botonRegistrar.setBorder(null);
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.setFocusable(false);
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseClicked(evt);
            }
        });
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonAtras.setEditable(false);
        botonAtras.setBackground(new java.awt.Color(231, 231, 231));
        botonAtras.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonAtras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonAtras.setText("ATRÁS");
        botonAtras.setAutoscrolls(false);
        botonAtras.setBorder(null);
        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras.setFocusable(false);
        botonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtrasMouseClicked(evt);
            }
        });
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        txtField_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_modeloActionPerformed(evt);
            }
        });

        txtField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_nombreActionPerformed(evt);
            }
        });

        txtField_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_marcaActionPerformed(evt);
            }
        });

        lbl_titulo.setBackground(new java.awt.Color(0, 0, 0));
        lbl_titulo.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        lbl_titulo.setText("DATOS DEL VEHÍCULO");

        lbl_matricula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_matricula.setText("MATRÍCULA");

        lbl_modelo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_modelo.setText("MODELO");

        lbl_marca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_marca.setText("MARCA");

        lbl_apellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_apellido.setText("APELLIDO");

        lbl_anio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_anio.setText("AÑO");

        lbl_anio1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_anio1.setText("FechaCompra");

        txtField_fechaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_fechaCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_apellido)
                    .addComponent(txtField_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtField_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_modelo)
                                .addComponent(txtField_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_marca)
                            .addComponent(txtField_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField_fechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_matricula)
                                .addGap(166, 166, 166))
                            .addComponent(lbl_anio1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonAtras)))
                .addGap(18, 18, 18)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_nombre)
                        .addGap(2, 2, 2)
                        .addComponent(txtField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_apellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(lbl_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(141, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_matricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_modelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(lbl_marca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_anio1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_fechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseClicked
        String nombre_cliente =txtField_nombre.getText();
        String apellido_cliente = txtField_apellido.getText();
        String fecha_compra = txtField_fechaCompra.getText();
        String marca = txtField_marca.getText();
        String modelo = txtField_modelo.getText();
        String anio = txtField_anio.getText();
        String matricula = txtField_matricula.getText();
        if(insertarMatricula("Vehiculo_Matricula",matricula)){
        insertar("Vehiculo_Todo_Guayaquil","2", nombre_cliente, apellido_cliente, fecha_compra,marca, modelo, anio);
        }
    }//GEN-LAST:event_botonRegistrarMouseClicked

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO ad your handling code here:
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseClicked
        principalRegistro framePrincipal = new principalRegistro();

        framePrincipal.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonAtrasMouseClicked

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO ad your handling code here:
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void txtField_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_marcaActionPerformed

    private void txtField_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_modeloActionPerformed

    private void txtField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_nombreActionPerformed

    private void txtField_fechaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_fechaCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_fechaCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField botonAtras;
    private javax.swing.JTextField botonRegistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_anio;
    private javax.swing.JLabel lbl_anio1;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_matricula;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_titulo;
    private java.awt.TextField txtField_anio;
    private java.awt.TextField txtField_apellido;
    private java.awt.TextField txtField_fechaCompra;
    private java.awt.TextField txtField_marca;
    private java.awt.TextField txtField_matricula;
    private java.awt.TextField txtField_modelo;
    private java.awt.TextField txtField_nombre;
    // End of variables declaration//GEN-END:variables
}
