/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.registro;

import com.mycompany.crudsqlserver.java.ConexionSQLServer;
import com.principal.principalRegistro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.UUID;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class registroEmpleado extends javax.swing.JFrame {

    private String idEmpleado;

    /**
     * Creates new form registroCliente
     */
    public registroEmpleado() {
        initComponents();
        
 
    }
   private boolean insertarTelefono(String tabla , String telefono ) {
        String sql = "INSERT INTO " + tabla + " (id_Empleado,numero_Telefonico,id_Taller) VALUES (?,?,?)";
        ConexionSQLServer con = new ConexionSQLServer();
        Connection conexion = con.obtenerConexion();

    
        try {
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, this.idEmpleado);
            ps.setString(2, telefono);
            ps.setString(3, "2");

            int rows = ps.executeUpdate();

            if (rows > 0) {
                System.out.println("Telefono insertado con éxito");
                return true;
            } else {
                System.out.println("Error al insertar matrícula");
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
    
    
        }
        return false;
}
   public boolean insertar(String idTaller, String nombre, String cedula, String fechaComienzo, String salario) {
        this.idEmpleado = cedula;
        String sql = "INSERT INTO Empleado_Guayaquil (id_Empleado, id_Taller, Nombre_empleado, "
                + "Cedula_Empleado, Fecha_comienzo, Salario) VALUES (?, ?, ?, ?, ?, ?)";
        ConexionSQLServer con = new ConexionSQLServer();
        Connection conexion = con.obtenerConexion();

        try {
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, idEmpleado);
            ps.setString(2, idTaller);
            ps.setString(3, nombre);
            ps.setString(4, cedula);
            ps.setString(5, fechaComienzo);
            ps.setString(6, salario);

            int rows = ps.executeUpdate();

            if (rows > 0) {
                System.out.println("Empleado insertado con éxito");
                return true;
            } else {
                System.out.println("Error al insertar empleado");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
      return false;
    }
        //conexion.close();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JTextField();
        botonAtras = new javax.swing.JTextField();
        txtField_Tlf = new java.awt.TextField();
        txtField_salario = new java.awt.TextField();
        txtField_fecha = new java.awt.TextField();
        txtField_cedula = new java.awt.TextField();
        txtField_nombre = new java.awt.TextField();
        lbl_telefono = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_salario = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EPN CAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        botonRegistrar.setEditable(false);
        botonRegistrar.setBackground(new java.awt.Color(231, 231, 231));
        botonRegistrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonRegistrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonRegistrar.setText("REGISTRAR");
        botonRegistrar.setAutoscrolls(false);
        botonRegistrar.setBorder(null);
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.setFocusable(false);
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseClicked(evt);
            }
        });
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonAtras.setEditable(false);
        botonAtras.setBackground(new java.awt.Color(231, 231, 231));
        botonAtras.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonAtras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonAtras.setText("ATRÁS");
        botonAtras.setAutoscrolls(false);
        botonAtras.setBorder(null);
        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras.setFocusable(false);
        botonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtrasMouseClicked(evt);
            }
        });
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        txtField_Tlf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_TlfActionPerformed(evt);
            }
        });

        txtField_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_fechaActionPerformed(evt);
            }
        });

        txtField_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_cedulaActionPerformed(evt);
            }
        });

        lbl_telefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_telefono.setText("TELÉFONOS");

        lbl_titulo.setBackground(new java.awt.Color(0, 0, 0));
        lbl_titulo.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        lbl_titulo.setText("DATOS DEL EMPLEADO");

        lbl_salario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_salario.setText("SALARIO");

        lbl_cedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_cedula.setText("CÉDULA");

        lbl_nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_nombre.setText("NOMBRE");

        lbl_fecha.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_fecha.setText("FECHA DE CONTRATACIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cedula)
                    .addComponent(txtField_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_salario)
                    .addComponent(lbl_fecha))
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(lbl_titulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre)
                            .addComponent(txtField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(226, 226, 226)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtField_Tlf, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_telefono))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonAtras)))
                .addGap(35, 35, 35)
                .addComponent(lbl_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cedula)
                    .addComponent(lbl_salario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(lbl_fecha)
                .addGap(1, 1, 1)
                .addComponent(txtField_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_Tlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseClicked
         // Reemplazar con el valor correcto
        String idTaller = "2";   // Reemplazar con el valor correcto
        String nombre =  txtField_nombre.getText();  // Reemplazar con el valor correcto
        String cedula = txtField_cedula.getText();  // Reemplazar con el valor correcto
        String fechaComienzo = txtField_fecha.getText();  // Reemplazar con el valor correcto
        String salario = txtField_salario.getText();  // Reemplazar con el valor correcto
        String telefono = txtField_Tlf.getText();
        // Insertar empleado
        if(insertar(idTaller, nombre, cedula, fechaComienzo, salario)){
            insertarTelefono("Telefono_Guayaquil",telefono);
        }
    }//GEN-LAST:event_botonRegistrarMouseClicked

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
       
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseClicked
        principalRegistro framePrincipal = new principalRegistro();

        framePrincipal.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonAtrasMouseClicked

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO ad your handling code here:
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void txtField_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_cedulaActionPerformed

    private void txtField_TlfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_TlfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_TlfActionPerformed

    private void txtField_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_fechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField botonAtras;
    private javax.swing.JTextField botonRegistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_salario;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_titulo;
    private java.awt.TextField txtField_Tlf;
    private java.awt.TextField txtField_cedula;
    private java.awt.TextField txtField_fecha;
    private java.awt.TextField txtField_nombre;
    private java.awt.TextField txtField_salario;
    // End of variables declaration//GEN-END:variables
}
