/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.principal;


import com.eleccion.eleccion;
import com.mycompany.crudsqlserver.java.ConexionSQLServer;
import com.registro.registroArticulo;
import com.registro.registroCliente;
import com.registro.registroEmpleado;
import com.registro.registroReparacion;
import com.registro.registroVehiculo;

/**
 *
 * @author alejo
 */
public class principalRegistro extends javax.swing.JFrame {

    /**
     * Creates new form eleccion
     */
    public principalRegistro() {
        initComponents();
    }

        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        botonRegistrarReparación = new javax.swing.JTextField();
        botonRegistrarArticulo = new javax.swing.JTextField();
        botonRegistrarVehiculo = new javax.swing.JTextField();
        botonRegistrarUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        botonRegistrarEmpleado = new javax.swing.JTextField();
        botonAtras1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel3.setText("REGISTRAR");

        botonRegistrarReparación.setEditable(false);
        botonRegistrarReparación.setBackground(new java.awt.Color(197, 197, 197));
        botonRegistrarReparación.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonRegistrarReparación.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonRegistrarReparación.setText("REPARACIÓN");
        botonRegistrarReparación.setAutoscrolls(false);
        botonRegistrarReparación.setBorder(null);
        botonRegistrarReparación.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarReparación.setFocusable(false);
        botonRegistrarReparación.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarReparaciónMouseClicked(evt);
            }
        });
        botonRegistrarReparación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarReparaciónActionPerformed(evt);
            }
        });

        botonRegistrarArticulo.setEditable(false);
        botonRegistrarArticulo.setBackground(new java.awt.Color(197, 197, 197));
        botonRegistrarArticulo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonRegistrarArticulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonRegistrarArticulo.setText("ARTICULO");
        botonRegistrarArticulo.setAutoscrolls(false);
        botonRegistrarArticulo.setBorder(null);
        botonRegistrarArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarArticulo.setFocusable(false);
        botonRegistrarArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarArticuloMouseClicked(evt);
            }
        });
        botonRegistrarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarArticuloActionPerformed(evt);
            }
        });

        botonRegistrarVehiculo.setEditable(false);
        botonRegistrarVehiculo.setBackground(new java.awt.Color(197, 197, 197));
        botonRegistrarVehiculo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonRegistrarVehiculo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonRegistrarVehiculo.setText("VEHÍCULO");
        botonRegistrarVehiculo.setAutoscrolls(false);
        botonRegistrarVehiculo.setBorder(null);
        botonRegistrarVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarVehiculo.setFocusable(false);
        botonRegistrarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarVehiculoMouseClicked(evt);
            }
        });
        botonRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarVehiculoActionPerformed(evt);
            }
        });

        botonRegistrarUsuario.setEditable(false);
        botonRegistrarUsuario.setBackground(new java.awt.Color(197, 197, 197));
        botonRegistrarUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonRegistrarUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonRegistrarUsuario.setText("USUARIO");
        botonRegistrarUsuario.setAutoscrolls(false);
        botonRegistrarUsuario.setBorder(null);
        botonRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarUsuario.setFocusable(false);
        botonRegistrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarUsuarioMouseClicked(evt);
            }
        });
        botonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarUsuarioActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EPN CAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        botonRegistrarEmpleado.setEditable(false);
        botonRegistrarEmpleado.setBackground(new java.awt.Color(197, 197, 197));
        botonRegistrarEmpleado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonRegistrarEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonRegistrarEmpleado.setText("EMPLEADO");
        botonRegistrarEmpleado.setAutoscrolls(false);
        botonRegistrarEmpleado.setBorder(null);
        botonRegistrarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarEmpleado.setFocusable(false);
        botonRegistrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarEmpleadoMouseClicked(evt);
            }
        });
        botonRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarEmpleadoActionPerformed(evt);
            }
        });

        botonAtras1.setEditable(false);
        botonAtras1.setBackground(new java.awt.Color(231, 231, 231));
        botonAtras1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonAtras1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonAtras1.setText("ATRÁS");
        botonAtras1.setAutoscrolls(false);
        botonAtras1.setBorder(null);
        botonAtras1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras1.setFocusable(false);
        botonAtras1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtras1MouseClicked(evt);
            }
        });
        botonAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(botonAtras1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(210, 210, 210)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonRegistrarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonRegistrarReparación, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonRegistrarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(190, 190, 190)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(botonAtras1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(botonRegistrarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(botonRegistrarReparación, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(botonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(botonRegistrarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarReparaciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarReparaciónMouseClicked
       registroReparacion frameRegistroReparacion = new registroReparacion();
       
        frameRegistroReparacion.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonRegistrarReparaciónMouseClicked

    private void botonRegistrarReparaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarReparaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarReparaciónActionPerformed

    private void botonRegistrarArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarArticuloMouseClicked
       registroArticulo frameRegistroArticulo = new registroArticulo();

        frameRegistroArticulo.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonRegistrarArticuloMouseClicked

    private void botonRegistrarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarArticuloActionPerformed

    private void botonRegistrarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarVehiculoMouseClicked
       registroVehiculo frameRegistroVehiculo = new registroVehiculo();

        frameRegistroVehiculo.setVisible(true);
    }//GEN-LAST:event_botonRegistrarVehiculoMouseClicked

    private void botonRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarVehiculoActionPerformed

    private void botonRegistrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarUsuarioMouseClicked
        registroCliente frameRegistroUsuario = new registroCliente();

        frameRegistroUsuario.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonRegistrarUsuarioMouseClicked

    private void botonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarUsuarioActionPerformed

    private void botonRegistrarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarEmpleadoMouseClicked
     registroEmpleado frameRegistroEmpleado = new registroEmpleado();

        frameRegistroEmpleado.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonRegistrarEmpleadoMouseClicked

    private void botonRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarEmpleadoActionPerformed

    private void botonAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtras1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAtras1ActionPerformed

    private void botonAtras1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtras1MouseClicked
        eleccion framePrincipal = new eleccion();

        framePrincipal.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonAtras1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField botonAtras1;
    private javax.swing.JTextField botonRegistrarArticulo;
    private javax.swing.JTextField botonRegistrarEmpleado;
    private javax.swing.JTextField botonRegistrarReparación;
    private javax.swing.JTextField botonRegistrarUsuario;
    private javax.swing.JTextField botonRegistrarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
