/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.principal;

import com.eleccion.*;
import consulta.ConsultarArticulo;
import consulta.ConsultarCliente;
import consulta.ConsultarEmpleado;
import consulta.ConsultarReparacion;
import consulta.ConsultarVehiculo;

/**
 *
 * @author alejo
 */
public class principalConsulta extends javax.swing.JFrame {

    /**
     * Creates new form eleccion
     */
    public principalConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        botonConsultarReparación = new javax.swing.JTextField();
        botonConsultarArticulo = new javax.swing.JTextField();
        botonConsultarVehiculo = new javax.swing.JTextField();
        botonConsultarUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        botonAtras = new javax.swing.JTextField();
        botonConsultarEmpleado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel2.setText("CONSULTAR");

        botonConsultarReparación.setEditable(false);
        botonConsultarReparación.setBackground(new java.awt.Color(197, 197, 197));
        botonConsultarReparación.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonConsultarReparación.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonConsultarReparación.setText("REPARACIÓN");
        botonConsultarReparación.setAutoscrolls(false);
        botonConsultarReparación.setBorder(null);
        botonConsultarReparación.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultarReparación.setFocusable(false);
        botonConsultarReparación.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsultarReparaciónMouseClicked(evt);
            }
        });
        botonConsultarReparación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarReparaciónActionPerformed(evt);
            }
        });

        botonConsultarArticulo.setEditable(false);
        botonConsultarArticulo.setBackground(new java.awt.Color(197, 197, 197));
        botonConsultarArticulo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonConsultarArticulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonConsultarArticulo.setText("ARTICULO");
        botonConsultarArticulo.setAutoscrolls(false);
        botonConsultarArticulo.setBorder(null);
        botonConsultarArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultarArticulo.setFocusable(false);
        botonConsultarArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsultarArticuloMouseClicked(evt);
            }
        });
        botonConsultarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarArticuloActionPerformed(evt);
            }
        });

        botonConsultarVehiculo.setEditable(false);
        botonConsultarVehiculo.setBackground(new java.awt.Color(197, 197, 197));
        botonConsultarVehiculo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonConsultarVehiculo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonConsultarVehiculo.setText("VEHÍCULO");
        botonConsultarVehiculo.setAutoscrolls(false);
        botonConsultarVehiculo.setBorder(null);
        botonConsultarVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultarVehiculo.setFocusable(false);
        botonConsultarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsultarVehiculoMouseClicked(evt);
            }
        });
        botonConsultarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarVehiculoActionPerformed(evt);
            }
        });

        botonConsultarUsuario.setEditable(false);
        botonConsultarUsuario.setBackground(new java.awt.Color(197, 197, 197));
        botonConsultarUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonConsultarUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonConsultarUsuario.setText("USUARIO");
        botonConsultarUsuario.setAutoscrolls(false);
        botonConsultarUsuario.setBorder(null);
        botonConsultarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultarUsuario.setFocusable(false);
        botonConsultarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsultarUsuarioMouseClicked(evt);
            }
        });
        botonConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarUsuarioActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EPN CAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        botonAtras.setEditable(false);
        botonAtras.setBackground(new java.awt.Color(231, 231, 231));
        botonAtras.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonAtras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonAtras.setText("ATRAS");
        botonAtras.setAutoscrolls(false);
        botonAtras.setBorder(null);
        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras.setFocusable(false);
        botonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtrasMouseClicked(evt);
            }
        });
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonConsultarEmpleado.setEditable(false);
        botonConsultarEmpleado.setBackground(new java.awt.Color(197, 197, 197));
        botonConsultarEmpleado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        botonConsultarEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        botonConsultarEmpleado.setText("EMPLEADO");
        botonConsultarEmpleado.setAutoscrolls(false);
        botonConsultarEmpleado.setBorder(null);
        botonConsultarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultarEmpleado.setFocusable(false);
        botonConsultarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsultarEmpleadoMouseClicked(evt);
            }
        });
        botonConsultarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(210, 210, 210)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(botonConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonConsultarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonConsultarReparación, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonConsultarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonConsultarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(190, 190, 190)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(botonConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(botonConsultarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(botonConsultarReparación, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(botonConsultarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(botonConsultarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarReparaciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarReparaciónMouseClicked
         ConsultarReparacion frameRegistroReparacion = new ConsultarReparacion();

        frameRegistroReparacion.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_botonConsultarReparaciónMouseClicked

    private void botonConsultarReparaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarReparaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarReparaciónActionPerformed

    private void botonConsultarArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarArticuloMouseClicked
        ConsultarArticulo frameConsultarArticulo = new ConsultarArticulo();

        frameConsultarArticulo.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonConsultarArticuloMouseClicked

    private void botonConsultarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarArticuloActionPerformed

    private void botonConsultarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarVehiculoMouseClicked
       ConsultarVehiculo frameConsultarVehiculo = new ConsultarVehiculo();

        frameConsultarVehiculo.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_botonConsultarVehiculoMouseClicked

    private void botonConsultarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarVehiculoActionPerformed

    private void botonConsultarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarUsuarioMouseClicked
        ConsultarCliente frameConsultarUsuario = new ConsultarCliente();
        frameConsultarUsuario.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonConsultarUsuarioMouseClicked

    private void botonConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarUsuarioActionPerformed

    private void botonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseClicked
        eleccion framePrincipal = new eleccion();

        framePrincipal.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonAtrasMouseClicked

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed

    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonConsultarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarEmpleadoMouseClicked
       ConsultarEmpleado frameConsultarEmpleado = new ConsultarEmpleado();

        frameConsultarEmpleado.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_botonConsultarEmpleadoMouseClicked

    private void botonConsultarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField botonAtras;
    private javax.swing.JTextField botonConsultarArticulo;
    private javax.swing.JTextField botonConsultarEmpleado;
    private javax.swing.JTextField botonConsultarReparación;
    private javax.swing.JTextField botonConsultarUsuario;
    private javax.swing.JTextField botonConsultarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
